### ISSUE TITLE
Duplicate trip sensors on 2020 Toyota RAV4

### ISSUE THREAD

**Issue by SeanPM5** [widewing/ha-toyota-na#2]
First off thanks for the great work on this component! 

I noticed there is a duplicate sensors for trip data on my 2020 Toyota RAV4. The top two in this picture appear to be the correct ones, and bottom two appear with a wrong icon (`mdi:car-door`), unrounded state value, and different unit of measurement than the rest (`miles` instead of `mi`).

![sensors](https://i.imgur.com/dJuy8B3.png)

Is not a big deal, easy to ignore/disable them, just letting you know.

**Comment by widewing** [comment]
yes, the reason is the first two readings (Trip A/B Toyota RAV4) are collected specifically for trip readings; while the other two (Trip Details Trip A/B Toyota RAV4) are collected from the same object with other door status. actually the "72.2 miles" is a complete string instead of "72.2" as value and "miles" as measurement unit. I think maybe it's better not to hard code to exclude them specifically

**Comment by SeanPM5** [comment]
Alright thanks :)
