### ISSUE TITLE
Sensors issue

### ISSUE THREAD

**Issue by kyle4269** [widewing/ha-toyota-na#41]
I'm not receiving an error when I setup this integration. My problem is, once I add the integration, HA is not showing any sensors for the truck.
[config_entry-toyota_na-16d67e53df81cee9149fe9d1974408d6.json.txt](https://github.com/widewing/ha-toyota-na/files/8598876/config_entry-toyota_na-16d67e53df81cee9149fe9d1974408d6.json.txt)

**Comment by jlmaners** [comment]
This is due to the fact of a new generation of vehicle that we haven't seen before - 21MM.

We'll need to investigate to see if there are differing endpoints needed for these newer generation vehicles but it will likely be a little bit of time before we can patch this. Would you be willing/available to help us test as none of us own a vehicle of this generation.

**Comment by kyle4269** [comment]
Absolutely! Let me know what you need me to do. Thank you!

**Comment by vanstinator** [comment]
I think we've spotted the bug. I'll but together a build later today that hopefully gets you on your feet.

**Comment by kyle4269** [comment]
Great! I'll give it a try when you guys are done.

**Comment by vanstinator** [comment]
The release is building now and should be available in HACS shortly

**Comment by kyle4269** [comment]
[Error1.txt](https://github.com/widewing/ha-toyota-na/files/8599911/Error1.txt)
[error2.txt](https://github.com/widewing/ha-toyota-na/files/8599913/error2.txt)
[Error3.txt](https://github.com/widewing/ha-toyota-na/files/8599916/Error3.txt)
